apiVersion: v1
data:
  tokens.json: W3sidG9rZW4iOiAiYmVuY2htYXJrIn1d
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter-benchmark
type: Opaque
