apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  creationTimestamp: null
  labels:
    machineconfiguration.openshift.io/role: master
  name: 99-master-ssh
spec:
  config:
    ignition:
      version: 3.1.0
    passwd:
      users:
      - name: core
        sshAuthorizedKeys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD14Gv4V5DVvyr7O6/44laYx52VYLe8yrEA3fOieWDmojRs3scqLnfeLHJWsfYA4QMjTuraLKhT8dhETSYiSR88RMM56+isLbcLshE6GkNkz3MBZE2hcdakqMDm6vucP3dJD6snuh5Hfpq7OWDaTcC0zCAzNECJv8F7LcWVa8TLpyRgpek4U022T5otE1ZVbNFqN9OrGHgyzVQLtC4xN1yT83ezo3r+OEdlSVDRQfsq73Zg26d4dyagb6lmrryUUAAbfmn/HalJTHB73LyjilKiPvJ+x2bG7AeiqyVHwtQSpt02FCdQGptmsSqqWF/b9botOO38eUsqPNppMn7LT5wzDZdDlfwTCBWkpqijPcdo/LTD9dJlNHjwXZtHETtiid6N3ZZWpA0/VKjqUeQdSnHqLEzTidswsnOjCIoIhmJFqczeP5kOty/MWdq1II/FX/EpYCJxoSWkT/hVwD6VOamGwJbLVw9LkEb0VVWFRJB5suT/T8DtPdPl+A0qUGiN4KM= oscohen@localhost.localdomain
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDd84cK8wIaqB7LKAfJ4354dkqe1sywdw9KehVdiupseMzrkmX72Kn2vtZwSYU+xQvmJPfJxOnGCH6DIjN4fwph8jLoQD3bw1b0pLc6vXFm5ekN3472BHHJHUcl22MXeOcLBVLiqr30sZ8WT7RFdwe9glu2W+RlVWetb/fUxQFm2ce67DmT1cVWWKtVGBcfKwavYGb+gs2EPX3vu0OVHO+yyVV/FaCDwUEzRrcg0O4NX5jL3nqd6kXvuVZv9yGIrAyeZUvAQYwf2Ls4/++Cp0Z1BVW2u54sTX2rE2OAQl+FxvFS28sHvlrDGB4ING/2s9nQ/Rb01riaSiP2Bc1OdTYt ybettan@dhcp-3-107.tlv.redhat.com
  fips: false
  kernelArguments: null
  kernelType: null
  osImageURL: null
